[application]

# Keys
api_key_names = ["RAPIDAPI_KEY"]

# URLs
postgres_url = "POSTGRES_URL"

# Names
database_name = "stonks-dev"

# Display
outro_duration_seconds = 5

# Logs
log_level = "DEBUG"

# Paths
input_file_path = "input/s&p500.json"
log_directory_path = "logs/"
storage_directory_path = "data/s&p500/"
output_directory_path = "output/"

# Flags
request_new_data = true
store_new_data = true
