[application]
version = "1.0.0-pre-alpha"
authors = ["Thomas Ashley"]

api_key_names = ["RAPIDAPI_KEY"]

outro_duration_seconds=5

log_level = "DEBUG"
log_directory = "logs/"

input_directory = "input/"

storage_directory = "data/"

request_new_data = true
store_new_data = true
