[application]
version = "0.0.0"
authors = ["Tom Ashley"]

log_level = "DEBUG"
log_directory = "logs/"

input_directory = "input/"

storage_directory = "data/"

request_new_data = true
store_new_data = true
