[application]

api_key_names = ["RAPIDAPI_KEY"]

outro_duration_seconds=5

log_level = "DEBUG"
log_directory = "logs/"

input_directory = "input/"
input_file = "input.json"

storage_directory = "data/"

request_new_data = true
store_new_data = true
