[application]

# Keys
api_key_names = ["RAPIDAPI_KEY"]

# Displays
outro_duration_seconds=5

# Logs
log_level = "DEBUG"

# Paths
input_file = "input/s&p500.json"
log_directory = "logs/"
storage_directory = "data/s&p500/"
output_directory = "output/"

# Flags
request_new_data = true
store_new_data = true
